// <auto-generated />
using System;
using BiblioUniversity.Infraestructure.BaseDatosContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiblioUniversity.Infraestructure.Migrations
{
    [DbContext(typeof(BiblioContext))]
    [Migration("20250820220813_adfaf")]
    partial class adfaf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 1
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 3
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 4
                        });
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url_digital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Edition = "1ra",
                            Pages = 256,
                            Title = "Ultimate Python: de cero a experto",
                            Url_digital = "",
                            Url_image = ""
                        },
                        new
                        {
                            Id = 2,
                            Edition = "1ra",
                            Pages = 234,
                            Title = "Aprendiendo Git y Github",
                            Url_digital = "",
                            Url_image = ""
                        },
                        new
                        {
                            Id = 3,
                            Edition = "1ra",
                            Pages = 456,
                            Title = "Clean Code",
                            Url_digital = "",
                            Url_image = ""
                        },
                        new
                        {
                            Id = 4,
                            Edition = "1ra",
                            Pages = 624,
                            Title = "Ultimate TypeScript: Guía completa para principiantes (Spanish Edition)",
                            Url_digital = "",
                            Url_image = ""
                        });
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.DataOnly.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Robert C. Martin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Miguel Angel Duran Garcia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nicolas Schurmann"
                        });
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.DataOnly.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "20250347"
                        },
                        new
                        {
                            Id = 2,
                            Code = "20254533"
                        },
                        new
                        {
                            Id = 3,
                            Code = "20259865"
                        },
                        new
                        {
                            Id = 4,
                            Code = "20255467"
                        });
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.DataOnly.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Software"
                        });
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.DataOnly.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Español"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ingles"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Frances"
                        });
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Fine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amaunt")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Fine_Status")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Librarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("License")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Librarianes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            License = "B02342",
                            PersonId = 5
                        },
                        new
                        {
                            Id = 2,
                            License = "B03342",
                            PersonId = 6
                        });
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id_Card")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Card")
                        .IsUnique();

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Los Alcarrizos",
                            Id_Card = "40214335478",
                            Lastname = "Perez Mendosa",
                            Name = "Fernando Garcia",
                            Telephone = "8097896786"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Los Mina",
                            Id_Card = "40234544556",
                            Lastname = "Ramirez Carrasco",
                            Name = "Pedro Alvarez",
                            Telephone = "8295678976"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Santo Domingo Este",
                            Id_Card = "40298765432",
                            Lastname = "Gomez Castillo",
                            Name = "Laura Martinez",
                            Telephone = "8092345678"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Villa Mella",
                            Id_Card = "40287654321",
                            Lastname = "Torres Mejia",
                            Name = "Jose Ramirez",
                            Telephone = "8293456789"
                        },
                        new
                        {
                            Id = 5,
                            Address = "San Cristobal",
                            Id_Card = "40276543210",
                            Lastname = "Lopez Santana",
                            Name = "Carla Fernandez",
                            Telephone = "8494567890"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Boca Chica",
                            Id_Card = "40265432109",
                            Lastname = "Morales Diaz",
                            Name = "Luis Castillo",
                            Telephone = "8095678901"
                        },
                        new
                        {
                            Id = 7,
                            Address = "La Capital",
                            Id_Card = "43123435654",
                            Lastname = "Benedict Torvalds",
                            Name = "Linus",
                            Telephone = "8297768909"
                        });
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantify")
                        .HasColumnType("int");

                    b.Property<DateTime>("Request_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Return_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Withdrawal_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("StudentId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Stock_Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Available")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Existing")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = 10,
                            BookId = 1,
                            Existing = 11
                        },
                        new
                        {
                            Id = 2,
                            Available = 10,
                            BookId = 2,
                            Existing = 11
                        },
                        new
                        {
                            Id = 3,
                            Available = 10,
                            BookId = 3,
                            Existing = 11
                        },
                        new
                        {
                            Id = 4,
                            Available = 10,
                            BookId = 4,
                            Existing = 11
                        });
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentId = 1,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentId = 2,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 3,
                            EnrollmentId = 3,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 4,
                            EnrollmentId = 4,
                            PersonId = 4
                        });
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "20250347",
                            PersonId = 1,
                            Rol = 2,
                            Username = "20250347"
                        },
                        new
                        {
                            Id = 2,
                            Password = "20254533",
                            PersonId = 2,
                            Rol = 2,
                            Username = "20254533"
                        },
                        new
                        {
                            Id = 3,
                            Password = "20259865",
                            PersonId = 3,
                            Rol = 2,
                            Username = "20259865"
                        },
                        new
                        {
                            Id = 4,
                            Password = "20255467",
                            PersonId = 4,
                            Rol = 2,
                            Username = "20255467"
                        },
                        new
                        {
                            Id = 5,
                            Password = "B02342",
                            PersonId = 5,
                            Rol = 1,
                            Username = "B02342"
                        },
                        new
                        {
                            Id = 6,
                            Password = "B03342",
                            PersonId = 6,
                            Rol = 1,
                            Username = "B03342"
                        },
                        new
                        {
                            Id = 7,
                            Password = "123",
                            PersonId = 7,
                            Rol = 0,
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("BookGenre");

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            GenresId = 1
                        },
                        new
                        {
                            BooksId = 2,
                            GenresId = 1
                        },
                        new
                        {
                            BooksId = 3,
                            GenresId = 1
                        },
                        new
                        {
                            BooksId = 4,
                            GenresId = 1
                        });
                });

            modelBuilder.Entity("BookLanguage", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("LanguagesId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "LanguagesId");

                    b.HasIndex("LanguagesId");

                    b.ToTable("BookLanguage");

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            LanguagesId = 1
                        },
                        new
                        {
                            BooksId = 2,
                            LanguagesId = 1
                        },
                        new
                        {
                            BooksId = 3,
                            LanguagesId = 2
                        },
                        new
                        {
                            BooksId = 4,
                            LanguagesId = 1
                        });
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("BiblioUniversity.Domain.Entities.DataOnly.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiblioUniversity.Domain.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Fine", b =>
                {
                    b.HasOne("BiblioUniversity.Domain.Entities.Reservation", "Reservation")
                        .WithOne("Fine")
                        .HasForeignKey("BiblioUniversity.Domain.Entities.Fine", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Librarian", b =>
                {
                    b.HasOne("BiblioUniversity.Domain.Entities.Person", "Person")
                        .WithOne("Librarian")
                        .HasForeignKey("BiblioUniversity.Domain.Entities.Librarian", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("BiblioUniversity.Domain.Entities.Book", "Book")
                        .WithMany("Reservations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiblioUniversity.Domain.Entities.Student", "Student")
                        .WithMany("Reservations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Stock_Book", b =>
                {
                    b.HasOne("BiblioUniversity.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Student", b =>
                {
                    b.HasOne("BiblioUniversity.Domain.Entities.DataOnly.Enrollment", "Enrollment")
                        .WithOne("Student")
                        .HasForeignKey("BiblioUniversity.Domain.Entities.Student", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiblioUniversity.Domain.Entities.Person", "Person")
                        .WithOne("Student")
                        .HasForeignKey("BiblioUniversity.Domain.Entities.Student", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.User", b =>
                {
                    b.HasOne("BiblioUniversity.Domain.Entities.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("BiblioUniversity.Domain.Entities.User", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("BiblioUniversity.Domain.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiblioUniversity.Domain.Entities.DataOnly.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookLanguage", b =>
                {
                    b.HasOne("BiblioUniversity.Domain.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiblioUniversity.Domain.Entities.DataOnly.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Book", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.DataOnly.Enrollment", b =>
                {
                    b.Navigation("Student")
                        .IsRequired();
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Person", b =>
                {
                    b.Navigation("Librarian")
                        .IsRequired();

                    b.Navigation("Student")
                        .IsRequired();

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Fine")
                        .IsRequired();
                });

            modelBuilder.Entity("BiblioUniversity.Domain.Entities.Student", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
