@startuml

skinparam Class {
    BackgroundColor<<Entidad>> LightGreen
    BackgroundColor<<Dato_Unico>> LightBlue
    BackgroundColor<<Relacion>> LightCoral
    BackgroundColor<<Entidad_de_Control>> LightYellow
    BackgroundColor<<Enum>> LightGrey
}

Class Persona <<Entidad>>{
    +Id : int,
    +Nombre: string,
    +Apellido: string,
    +Telefono: string,
    +Cedula: string,
    +Direccion: string,
    
}

Class Usuario <<Entidad>>{
    +Id: int,
    +Persona: Persona,
    +Usuario: string,
    +Contraseña: string,
    +Rol: Rol
}

Class Estudiante <<Entidad>>{
    +Id: int,
    +Persona: Persona,
    +Matricula: Matricula,
}

class Matricula <<Dato_Unico>>{
    +Id: int,
    +Matricula: string
}
Class Bibliotecario <<Entidad>>{
    +Id: int,
    +Persona: Persona,
    +Carnet: string,
}

Class Libro <<Entidad>>{
    +Id: int,
    +Titulo: string,
    +Edicion: string,
    +Editorial: string,
    +Autor: Autor,
    +Idioma: Idioma,
    +Paginas: int,
    +Url_Imagen: string,
    +Url_VersionDigital: string,
}

Class Stock_Libros <<Entidad_de_Control>>{
    +Id: int,
    +Libro: Libro,
    +Cant_Existente: int,
    +Cant_Disponible: int
}

Class Autor <<Dato_Unico>>{
    +Id: int,
    +Nombre: string,
}

Class Idioma <<Dato_Unico>>{
    +Id: int,
    +Idioma: string,
}

Class Genero <<Dato_Unico>>{
    +Id: int,
    +Genero: string,
}

Class Prestamo <<Entidad>>{
    +Id: int,
    +Estado: Estado_prestamo,
    +Tipo: Tipo_prestamo,
    +Estudiante: Estudiante,
    +Libro: Libro,
    +Cantidad: int,
    +Fecha_Solicitud: Datetime,
    +Fecha_Retiro: Datetime,
    +Fecha_Devolucion: Datetime
}

Class Multa <<Entidad>>{
    +Id: int,
    +Prestamo: Prestamo,
    +Descripcion: string,
    +Monto: int,
    +Estado: Estado_multa,
}

Class LibroGenero <<Relacion>>{
    Libro: Libro
    Genero: Genero
}

Class LibroAutor <<Relacion>>{
    Libro: Libro,
    Autor: Autor
}
enum Rol{
    Admin,
    Bibliotecario,
    Estudiante
}

enum Estado_multa{
    Pendiente,
    Pagada,
    Revocada,
}

enum Estado_prestamo{
    Pendiente,
    Aprobado,
    Rechazado
}

enum Tipo_prestamo{
    Solicitud_digital,
    Retiro_fisico
}

Usuario "1" *-- "1" Persona         
Usuario "1" *-- "1..*" Rol          

Estudiante "1" *-- "1" Persona     
Estudiante "1" -- "1" Matricula 
Bibliotecario "1" *-- "1" Persona   

Prestamo "1" -- "1" Libro
Prestamo "1" -- "1" Estudiante
Prestamo "1" *-- "1" Tipo_prestamo
Prestamo "1" *-- "1" Estado_prestamo

Multa "1" *-- "1" Prestamo
Multa "1" *-- "1" Estado_multa

Libro "1" -- "1..*" LibroGenero
Genero "1" -- "1..*" LibroGenero
Libro "1" *-- "1" Idioma
Libro "1" -- "1..*" LibroAutor
Autor "1" -- "0..*" LibroAutor

Stock_Libros "1" *-- "1" Libro : "Libro al que está\nEnlazado el stock"

@enduml
